FROM golang:alpine

RUN apk update \
    && apk add --no-cache gcc musl-dev \
    && apk add --no-cache sqlite sqlite-dev

COPY main.go /go/src
COPY go.mod /go/src

WORKDIR /go/src

RUN go build --tags "libsqlite3 linux" main.go

EXPOSE 8080

CMD ["./main"]
