version: "3"

services:

  cccc:
    build:
      context: .
      dockerfile: Dockerfile-cccc
    image: cccc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cccc/letsencrypt:/etc/letsencrypt
      - ./cccc/root:/etc/crontabs/root
      - ./cccc/nginx.conf:/etc/nginx/nginx.conf
      - ./cccc/conf.d:/etc/nginx/conf.d
      - ./cccc/log:/var/log/nginx
      - ./cccc/html:/usr/share/nginx/html
    environment:
      - DOMAIN=your.domain
      - EMAIL=your@email.address
      #- STAGE=production
      - STAGE=staging
    restart: always

  comento:
    build:
      context: .
      dockerfile: Dockerfile-comento
    image: comento
    volumes:
      - ./comento:/go/src/comento
    restart: always
